### ISSUE TITLE
copy semantics of Mesh class

### ISSUE THREAD

**Issue by jacobmerson** [sandialabs/omega_h#386]
I originally posted this in https://github.com/SCOREC/omega_h/issues/28 but @cwsmith suggested that I repost here to get input from @ibaned 

Looking at the Mesh class I'm not entirely sure 
```
Omega_h::Mesh mesh_a;
mesh_b = mesh_a; // most data is shared via internal shared ptrs, but not all!

mesh_b.set_dim(1); // dim is integer so copied by value...mesh dim in a still default value
mesh_b.set_coords(new_coords); // coords are a tag and tags are shared between mesh instances with shared ptr! now both mesh_a and mesh_b have new coords!
```
Also, you can't assume that the values stored internally as shared_ptrs will be shared between instances because some items like `set_parents()` assign a new shared_ptr, so assigning new values in one instance won't affect the other one.

I suspect most people are passing the mesh via ptr or reference and aren't actually copying a mesh instance which is why we haven't hit the nasty bug/confusion that this will cause.

Since copy doesn't do what people expect I suggest either deprecating or deleting the copy constructor/assignment until we decide on the intended semantics and fix the class to consistently abide by those semantics.

**Comment by ibaned** [comment]
Hi @jacobmerson !

The `Mesh` copy constructor is supposed to make the two meshes behave as though they don't share anything or know about each other. If `mesh_b.set_coords()` changes the coordinates of `mesh_a`, then that is the bug we should fix. Have you confirmed that that is what happens?

Again, the new mesh should not be able to affect the old mesh in any observable way, it should behave exactly as though they share nothing. The under-the-hood sharing of arrays that haven't changed is just an optimization but it shouldn't change behavior

**Comment by jacobmerson** [comment]
I'll put together a minimal example.

**Comment by jacobmerson** [comment]
@ibaned here is a minimal example (the actual code).
```c++
#include <Omega_h_build.hpp>
#include <Omega_h_library.hpp>
#include <Omega_h_mesh.hpp>
#include <Omega_h_compare.hpp>
#include <Omega_h_for.hpp>
#include <iostream>
using namespace Omega_h;

int main(int argc, char** argv) {
  auto lib = Library(&argc,&argv);
  auto world = lib.world();
  auto mesh_a = build_box(world, OMEGA_H_SIMPLEX, 1, 1, 1, 10, 10,10,false);
  auto mesh_b = mesh_a;
  // before copy we know that the address of
  Write<Real> new_coords(mesh_a.coords().size());
  Omega_h::parallel_for(new_coords.size(), OMEGA_H_LAMBDA(LO i){ new_coords[i]=5; });
  mesh_b.set_coords(new_coords);
  int count=0;
  for (auto& coord : mesh_a.coords() ) {
    // forgive this floating point comparison...
    if (coord == 5) ++count;
  }
  std::cout<<count<<" "<<mesh_a.coords().size()<<"\n";
  mesh_b.set_family(OMEGA_H_HYPERCUBE);
  std::cout<<mesh_a.family()<<" "<<mesh_b.family()<<"\n";

  return 0;
}
```
Which gives as output
```
3993 3993
0 1
```
So here you can see that mesh_a coords are getting set when modifying the mesh_b coords. I will also note it's not just the coords/tags, but much of that classes data which have the same problem.

**Comment by jacobmerson** [comment]
I just now saw that you have a commit regarding this issue. Based on the commentary there it seem you are intending copy on write semantics for the class? In that case how about we make all of the shared pointer types in `Mesh` into `shared_ptr<const T>`? That way the compiler will prevent us from not upholding COW semantics.

That is,
```c++
  typedef std::shared_ptr<TagBase> TagPtr;
  typedef std::shared_ptr<Adj> AdjPtr;
  typedef std::shared_ptr<Dist> DistPtr;
  typedef std::shared_ptr<inertia::Rib> RibPtr;
  typedef std::shared_ptr<Parents> ParentPtr;
  typedef std::shared_ptr<Children> ChildrenPtr;
```

goes to:

```c++
  typedef std::shared_ptr<const TagBase> TagPtr;
  typedef std::shared_ptr<const Adj> AdjPtr;
  typedef std::shared_ptr<const Dist> DistPtr;
  typedef std::shared_ptr<const inertia::Rib> RibPtr;
  typedef std::shared_ptr<const Parents> ParentPtr;
  typedef std::shared_ptr<const Children> ChildrenPtr;
```

If you conceptually agree I can put together a pull request.

**Comment by ibaned** [comment]
@jacobmerson if you can do this and all the tests still pass, I support it!

**Comment by ibaned** [comment]
This has been fixed, please comment if its still an issue
